### ISSUE TITLE
Progress Bar not appearing

### ISSUE THREAD

**Issue by acranej** [pymc-devs/nutpie#121]
The progress bar seems to have disappeared while using the nutpie sampler. Any ideas on why this happened or how to get it back?

**Comment by ricardoV94** [comment]
Are you sampling on the terminal?

**Comment by acranej** [comment]
I'm running in vscode. If I let pymc auto assign to NUTS I get the progress bar

**Comment by ricardoV94** [comment]
VScode jupyter notebook, or vscode terminal? The progressbar was changed recently and may not be compatible with some cases. CC @aseyboldt

**Comment by acranej** [comment]
I'm using vscode terminal. I just tried and it still works with NUTS. I'm running pymc v5.15.1, nutpie v0.11.0, numba v0.59.1

**Comment by ricardoV94** [comment]
Yes I think progressbar doesn't work on any terminals (not just vscode)

**Comment by acranej** [comment]
Interesting, on my end it seems specific to nutpie. Is there an alternative way you would suggest to have some idea of how much sampling has been done?

**Comment by ricardoV94** [comment]
It is specific to nutpie, nutpie implements it's own progressbar. Nothing to do with PyMC. I'll let @aseyboldt answer your question :)

**Comment by aseyboldt** [comment]
I might have been a bit too enthusiastic about having a fancy new progressbar in the notebook, and released a version without first also implementing a progressbar for the terminal again. Sorry about that.
It shouldn't be too difficult though, and I'll fix that in the next release (hopefully this week, also with a fix for a recent regression concerning some sample stats and a fix #120).

**Comment by acranej** [comment]
I can run it in notebook for now! Thanks for the help!

**Comment by aseyboldt** [comment]
I'll keep this open until a fix is released.
