### ISSUE TITLE
Use pymc's dlogp with rewrites

### ISSUE THREAD

**Issue by dehorsley** [pymc-devs/nutpie#45]
With https://github.com/pymc-devs/pymc/pull/6736 merged, pymc rewrites the logp graph before applying the gradient. This removes some Ops from the graph, which should have some performance benefits in general but mainly target at https://github.com/pymc-devs/pymc/issues/6717. Currently, nutpie calculates dlogp itself here:

https://github.com/pymc-devs/nutpie/blob/69eb0ce026c4183a88e3c099b4f329773fdcc151/nutpie/compile_pymc.py#L197

I think this can be replaced with a simple

```
grads = model.dlogp(value_vars) 
```

Though I think we can also drop the `value_vars`, it only seems to be used for the grad.

**Comment by aseyboldt** [comment]
I just included this in #42 (https://github.com/pymc-devs/nutpie/pull/42/commits/dc3cf2b0bc262eae3e01e2bc776f7b2661d2914c)
It would probably be cleaner to reuse some of the compilation machinery in pymc instead of building this again...
