### ISSUE TITLE
Uninformative stack traces on import errors

### ISSUE THREAD

**Issue by maresb** [pymc-devs/nutpie#67]
I think it'd help to put the import statements inside of `def compile_X_model`, because otherwise information about the `ImportError` isn't being passed on.

**Comment by canyon289** [comment]
Thanks Ben!!

**Comment by maresb** [comment]
Glad I could help @canyon289! Did my suggestion of running `from nutpie import compile_pymc` lead to more info?

I can open a PR for this shortly. This is a quick one, but it was too late for me last night.

**Comment by canyon289** [comment]
I didnt get a chance, I'll try it out tomorrow

**Comment by maresb** [comment]
Proposed fix is up in #72.

@canyon289 I'm still interested in knowing what went wrong with your environment, so please do send me the stack trace when you get the chance.

**Comment by canyon289** [comment]
It was this, this is way more informative!

![image](https://github.com/pymc-devs/nutpie/assets/7213793/85ad6408-d629-43bb-994b-128bc3e83486)

**Comment by maresb** [comment]
Thanks @canyon289! This should now be handled better by #72.
