### ISSUE TITLE
Missing numba leads to import error message complaining about missing PyMC even though PyMC is installed

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/nutpie#75]
I ran into this line `raise ValueError("Missing dependencies for pymc models. Install pymc.")` even though PyMC was installed.

Doing `import nutpie.compile_pymc` gave the actual import error: `ModuleNotFoundError: No module named 'numba'`

A `raise ImportError(...) from ex` might help to show the actual import error.

**Comment by michaelosthege** [comment]
it is closed then

**Comment by maresb** [comment]
Maybe better closed after a release?

**Comment by AlexAndorra** [comment]
Just ran into this issue on a Mac M2 with PyMC 5.10.4 and nutpie 0.9.1. Indeed, asking mamba to install numba solved the issue.
But I was surprised: isn't numba a dependency of nutpie?

**Comment by maresb** [comment]
Reopening because we don't yet have a release incorporating #72.

Nutpie can now be used as a backend with either Stan or PyMC. Since Numba is only a dependency when using PyMC it's no longer a required dependency. Thus if you want to use nutpie with PyMC you have to install Numba explicitly.

**Comment by AlexAndorra** [comment]
Makes sense, thanks @maresb !

**Comment by maresb** [comment]
Released!
