### ISSUE TITLE
ValueError to install `pymc` when other packages are not installed

### ISSUE THREAD

**Issue by wd60622** [pymc-devs/nutpie#77]
I'm getting ValueError to install pymc 
```text
Traceback (most recent call last):
  File "~/.../example.py", line 4, in <module>
    compile_pymc_model(None)
  File "~/.../.venv/lib/python3.9/site-packages/nutpie/__init__.py", line 9, in compile_pymc_model
    raise ValueError("Missing dependencies for pymc models. Install pymc.")
ValueError: Missing dependencies for pymc models. Install pymc.
```

To reproduce: 
```bash 
python -m venv .venv 
source .venv/bin/activate 
pip install pymc nutpie
python example.py
```

```python
# example.py
from nutpie import compile_pymc_model
compile_pymc_model(...)
```

The following gives the informative error that numba is missing

```python
 from nutpie.compile_pymc import compile_pymc_model
```

Maybe this would be avoided if conda was used, but I didn't think numba was a dependency of pymc. Either way, maybe the error can be passed along to user

EDIT: I am scanning the source code on main and it may not be an issue anymore. Please close stale

**Comment by maresb** [comment]
Ya, this is a duplicate of #75. I hope we got that fixed properly now. Let us know if you run into any further problems!
