### ISSUE TITLE
Publish pipeline fails with maturin 1.5

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/nutpie#99]
I made the 0.10 release, but it might need a bit longer for this to appear on pypi.

See https://github.com/PyO3/maturin/issues/1998

**Comment by aseyboldt** [comment]
I'm also pretty confused...
There was [this](https://github.com/PyO3/maturin/pull/1965) PR in maturin recently (and released in 1.5 2 weeks ago), which changed metadata in source distributions. Maybe that is somehow related? But it is failing with the wheel, not the source?

**Comment by maresb** [comment]
Maybe there is a bug (or interaction of edge cases) in PyPI? The publish step seems to fail-fast, so I'm not sure about the status of the sdist.

**Comment by aseyboldt** [comment]
I'll try to upload it locally, maybe that gives me some more info.

**Comment by aseyboldt** [comment]
I uploaded the artifacts manually, so the release is now available.
With a bit of luck this will be fixed somewhere when we make the next release...
